- name: Setup LAMP Stack with PHP, Apache, Composer, and Let's Encrypt
  hosts: myServer
  become: yes

  vars_prompt:
    - name: "php_version"
      prompt: "Enter PHP version (e.g., 7.4, 8.1, 8.2, 8.3)"
      private: no

  roles:
    - php
    - apache
    - composer
    - letsencrypt
