- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install Composer with PHP {{ php_version }}
  shell: |
    php{{ php_version }} /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Verify Composer installation
  command: composer --version
  register: composer_version

- debug:
    msg: "Installed Composer version: {{ composer_version.stdout }}"
